# Tugas 2 | Hitung Diskritisasi Data Iris

## Konsep Dasar

Diskritisasi data digunakan untuk membagi atribut-atribut yang sifatnya kontinu menjadi data dengan interval.

Hal ini dilakukan karena fitur nilai kontinu cenderung memiliki peluang korelasi yang lebih kecil dengan variabel target. Hal ini karena kita akan kesulitan untuk menafsirkan hasilnya.

Setelah diskritisasi variabel, kelompok yang sesuai dengan target dapat diinterpretasikan. Misalnya, atribut usia dapat didiskritkan ke dalam format seperti di bawah 18, 18-44, 44-60, diatas 60.

## Macam-macam Perhitungan Diskritisasi


1. *Equal Width Binning*

  *Equal width binning* adalah diskritisasi yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar.

  $$ w=\frac{x_{min}-x_{max}}k $$

  $$ v_i=x_{min}+i*w $$

2. *Equal Frequency Binning*
  
  *Equal frequency binning* adalah diskritisasi yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

## Implementasi pada Kode Python

Import library yang dibutuhkan.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn import preprocessing
import sklearn.cluster as cluster
import sklearn.metrics as metrics
from sklearn.preprocessing import MinMaxScaler

**1. Dikritisasi Equal With**

Mengambil informasi dataset.

In [ ]:
Data_Iris = pd.read_csv("https://raw.githubusercontent.com/ApoorvRusia/Naive-Bayes-classification-on-Iris-dataset/master/iris.csv")

Menampikan/membaca dataset Iris.

In [ ]:
Data_Iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
def equalwidth1(Data_Iris):
  Xmax=max(Data_Iris["sepal_length"])
  Xmin=min(Data_Iris["sepal_length"])

  w=(Xmax-Xmin)/5

  v1=Xmin+(1*w)
  v2=Xmin+(2*w)
  v3=Xmin+(3*w)
  v4=Xmin+(4*w)
  v5=Xmin+(5*w)


  for i in range(len(Data_Iris["sepal_length"])):
    if Data_Iris["sepal_length"][i]<=v1:
      Data_Iris["sepal_length"][i]="A"
    elif Data_Iris["sepal_length"][i]>v1 and Data_Iris["sepal_length"][i]<=v2:
      Data_Iris["sepal_length"][i]="B"
    elif Data_Iris["sepal_length"][i]>v2 and Data_Iris["sepal_length"][i]<=v3:
      Data_Iris["sepal_length"][i]="C"
    elif Data_Iris["sepal_length"][i]>v3 and Data_Iris["sepal_length"][i]<=v4:
      Data_Iris["sepal_length"][i]="D"
    else:
      Data_Iris["sepal_length"][i]="E"

def equalwidth2(Data_Iris):
  Xmax=max(Data_Iris["sepal_width"])
  Xmin=min(Data_Iris["sepal_width"])

  w=(Xmax-Xmin)/5

  v1=Xmin+(1*w)
  v2=Xmin+(2*w)
  v3=Xmin+(3*w)
  v4=Xmin+(4*w)
  v5=Xmin+(5*w)


  for i in range(len(Data_Iris["sepal_width"])):
    if Data_Iris["sepal_width"][i]<=v1:
      Data_Iris["sepal_width"][i]="A"
    elif Data_Iris["sepal_width"][i]>v1 and Data_Iris["sepal_width"][i]<=v2:
      Data_Iris["sepal_width"][i]="B"
    elif Data_Iris["sepal_width"][i]>v2 and Data_Iris["sepal_width"][i]<=v3:
      Data_Iris["sepal_width"][i]="C"
    elif Data_Iris["sepal_width"][i]>v3 and Data_Iris["sepal_width"][i]<=v4:
      Data_Iris["sepal_width"][i]="D"
    else:
      Data_Iris["sepal_width"][i]="E"

def equalwidth3(iris):
  Xmax=max(iris["petal_length"])
  Xmin=min(iris["petal_length"])

  w=(Xmax-Xmin)/5

  v1=Xmin+(1*w)
  v2=Xmin+(2*w)
  v3=Xmin+(3*w)
  v4=Xmin+(4*w)
  v5=Xmin+(5*w)


  for i in range(len(iris["petal_length"])):
    if iris["petal_length"][i]<=v1:
      iris["petal_length"][i]="A"
    elif iris["petal_length"][i]>v1 and iris["petal_length"][i]<=v2:
      iris["petal_length"][i]="B"
    elif iris["petal_length"][i]>v2 and iris["petal_length"][i]<=v3:
      iris["petal_length"][i]="C"
    elif iris["petal_length"][i]>v3 and iris["petal_length"][i]<=v4:
      iris["petal_length"][i]="D"
    else:
      iris["petal_length"][i]="E"

def equalwidth4(iris):
  Xmax=max(iris["petal_width"])
  Xmin=min(iris["petal_width"])

  w=(Xmax-Xmin)/5

  v1=Xmin+(1*w)
  v2=Xmin+(2*w)
  v3=Xmin+(3*w)
  v4=Xmin+(4*w)
  v5=Xmin+(5*w)


  for i in range(len(iris["petal_width"])):
    if iris["petal_width"][i]<=v1:
      iris["petal_width"][i]="A"
    elif iris["petal_width"][i]>v1 and iris["petal_width"][i]<=v2:
      iris["petal_width"][i]="B"
    elif iris["petal_width"][i]>v2 and iris["petal_width"][i]<=v3:
      iris["petal_width"][i]="C"
    elif iris["petal_width"][i]>v3 and iris["petal_width"][i]<=v4:
      iris["petal_width"][i]="D"
    else:
      iris["petal_width"][i]="E"

In [ ]:
def equalwidth(Iris):
  equalwidth1(Iris)
  equalwidth2(Iris)
  equalwidth3(Iris)
  equalwidth4(Iris)

In [ ]:
equalwidth(Data_Iris)
Data_Iris

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    sepal_length sepal_width petal_length petal_width    species
0              B           D            A           A     setosa
1              A           C            A           A     setosa
2              A           C            A           A     setosa
3              A           C            A           A     setosa
4              A           D            A           A     setosa
..           ...         ...          ...         ...        ...
145            D           C            D           E  virginica
146            C           B            D           D  virginica
147            D           C            D           D  virginica
148            C           C            D           E  virginica
149            C           C            D           D  virginica

[150 rows x 5 columns]

**2. Dikritisasi Equal Frequency**

Mengambil informasi dataset.

In [ ]:
Data_Iris = pd.read_csv("https://raw.githubusercontent.com/ApoorvRusia/Naive-Bayes-classification-on-Iris-dataset/master/iris.csv")

Menampikan/membaca dataset Iris.

In [ ]:
Data_Iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
data_sepal_length = Data_Iris[["sepal_length"]]
data_sepal_width = Data_Iris[["sepal_width"]]
data_petal_length = Data_Iris[["petal_length"]]
data_petal_width = Data_Iris[["petal_width"]]

In [ ]:
def qcut(col, k):
    intervals = pd.qcut(Data_Iris[col], k).value_counts().index.to_list()
    return [[interval.left, interval.right] for interval in intervals]

In [ ]:
interval_sepal_length = qcut("sepal_length", 3)
interval_sepal_width = qcut("sepal_width", 3)
interval_petal_length = qcut("petal_length", 3)
interval_petal_width = qcut("petal_width", 3)

print("interval sepal_length :", interval_sepal_length)
print("interval sepal_width  :", interval_sepal_width)
print("interval petal_length :", interval_petal_length)
print("interval petal_width  :", interval_petal_width)

interval sepal_length : [[5.4, 6.3], [4.2989999999999995, 5.4], [6.3, 7.9]]
interval sepal_width  : [[1.999, 2.9], [2.9, 3.2], [3.2, 4.4]]
interval petal_length : [[2.633, 4.9], [0.999, 2.633], [4.9, 6.9]]
interval petal_width  : [[0.867, 1.6], [0.099, 0.867], [1.6, 2.5]]

In [ ]:
def equalfreq(list_interval, col):
    # mendapatkan panjang interval
    length = len(list_interval)

    # mengurutkan interval
    sort_interval = np.sort(list_interval, axis=0)
    # mendapatkan Category dari interval
    categories = np.array([chr(65+i) for i in range(length)])[:, None]
    # combine into interval data
    intervals = np.hstack((sort_interval, categories))

    newCol = []
    for i, row in Data_Iris.iterrows():
        data = row[col]
        for interval in intervals:
            if data >= interval[0].astype(float) and data <= interval[1].astype(float):
                newCol.append(interval[2])
                break

    return np.array(newCol, dtype=str)

In [ ]:
Data_Iris["sepal_length"] = equalfreq(interval_sepal_length, "sepal_length")
Data_Iris["sepal_width"] = equalfreq(interval_sepal_width, "sepal_width")
Data_Iris["petal_length"] = equalfreq(interval_petal_length, "petal_length")
Data_Iris["petal_width"] = equalfreq(interval_petal_width, "petal_width")

In [ ]:
Data_Iris

    sepal_length sepal_width petal_length petal_width    species
0              A           C            A           A     setosa
1              A           B            A           A     setosa
2              A           B            A           A     setosa
3              A           B            A           A     setosa
4              A           C            A           A     setosa
..           ...         ...          ...         ...        ...
145            C           B            C           C  virginica
146            B           A            C           C  virginica
147            C           B            C           C  virginica
148            B           C            C           C  virginica
149            B           B            C           C  virginica

[150 rows x 5 columns]